### ISSUE TITLE
NLU service should work for any siteId

### ISSUE THREAD

**Issue by mathquis** [synesthesiam/rhasspy-nlu-hermes#1]
Looking at the code, it seems that this service only generate intent from text for a single siteId.

As this service is not a satellite service it should not be restricted to a single siteId.

**Comment by synesthesiam** [comment]
OK, I've tried to have the best of both worlds. With no `--siteId` parameter, it will accept *any* siteId. You can add multiple `--siteId` arguments to restrict the service to just those siteIds.

Thoughts?

**Comment by mathquis** [comment]
Any siteId is perfect!
As the MQTT broker should already only let the authenticated users in, restricting to multiple siteIds does not seem very useful but if it's already there why not ;)
